### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by armins2k** [x2c/homebridge-hdmi#1]
Hi,

how do I install the plugin if I have homebridge up and running on a Pi already?
Can I use 'sudo npm install -g homebridge-hdmi'??

Thanks!

**Comment by Deanmv** [comment]
I just did and it seems ok. Then just setup the config.js file correctly and it is all ok!

**Comment by x2c** [comment]
Hi, the only other dependency which is required to be installed is LibCEC https://github.com/Pulse-Eight/libcec

Otherwise yes if you already have Homebridge installed just run "sudo npm install -g homebridge-hdmi" and copy the config example.

Cheers
